# -*- coding: utf-8 -*-
"""Adaptive_eta_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPpGNijEWIr01qZiq2VTnDGSTnnGZf-G
"""

import numpy as np

EXP_POWER_UTILITY = 10**5
eta = np.float64(10.0)
d_max = 100.0


receiver_coordinates = (0.0, 0.0, 0.0)

import numpy as np
import math

c = 3 * 10**8                                    # propagation velocity in the free space [m/s]
h_BS = 3.5                                       # antenna height of the base station [m]
h_UT = 3.5                                       # antenna height of the user terminal [m]
h_E = 1                                          # effective environment height [m]
h_prime_BS = h_BS - h_E                          # effective antenna height of the base station [m]
h_prime_UT = h_UT - h_E                          # effective antenna height of the user terminal [m]

def get_distance2D(p1, p2):
    d = np.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)
    return d

def get_distance3D(p1, p2):
    d = np.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2 + (p1[2] - p2[2]) ** 2)
    return d

def get_PL_LOS(p1, p2, f_c):
    d_2D = get_distance2D(p1, p2)
    d_3D = get_distance3D(p1, p2)
    d_BP = (4 * h_prime_BS * h_prime_UT * f_c) / c
    if (d_2D < 10):
        if (d_3D >= 1) and (d_3D <= 150):
            PL_LOS = 32.4 + 17.3*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9))
    else:
        if (d_2D >= 10) and (d_2D <= d_BP):
            PL_LOS = 32.4 + 21*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9))
        elif (d_2D >= d_BP) and (d_2D <= 5 * 10**3):
            PL_LOS = 32.4 + 40*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9)) - 9.5*math.log10((d_BP)**2 + (p1[2] - p2[2])**2)
    return PL_LOS

def get_PL_NLOS(p1, p2, f_c):
    d_2D = get_distance2D(p1, p2)
    d_3D = get_distance3D(p1, p2)
    if (d_2D < 10):
        if (d_3D >= 1) and (d_3D <= 150):
            PL_prime_NLOS = 17.3 + 38.3*math.log10(d_3D) + 24.9*math.log10(f_c * 10**(-9))
    else:
        if (d_2D >= 10) and (d_2D <= 5 * 10**3):
            PL_prime_NLOS = 22.4 + 35.3*math.log10(d_3D) + 21.3*math.log10(f_c * 10**(-9)) - 0.3*(p2[2] - 1.5)
    PL_NLOS = max(get_PL_LOS(p1, p2, f_c), PL_prime_NLOS)
    return PL_NLOS

#this function gives the probability that how much of the transmission is in Line of Sight
def get_Pr(p1, p2):
    d_2D = get_distance2D(p1, p2)
    if (d_2D < 10):
        if (d_2D <= 1.2):
            pr_LOS = 1
        elif (d_2D > 1.2) and (d_2D < 6.5):
            pr_LOS = math.exp(-(d_2D - 1.2)/4.7)
        elif (d_2D >= 6.5):
            pr_LOS = math.exp(-(d_2D - 6.5)/32.6) * 0.32
    else:
        if d_2D <= 18:
            pr_LOS = 1
        elif d_2D > 18:
            pr_LOS = (18/d_2D) + (math.exp(-d_2D/36) * (1 - (18/d_2D)))
    return pr_LOS

def get_PL(p1, p2, f_c):
    PL = get_Pr(p1, p2) * get_PL_LOS(p1, p2, f_c) + (1 - get_Pr(p1, p2)) * get_PL_NLOS(p1, p2, f_c)
    return PL

def get_channel_gain(p1, p2, f_c):
    g = 1 / 10**(get_PL(p1, p2, f_c) / 10)
    return np.float64(g)

import numpy as np
import math

def get_distance2D(p1, p2):
    return np.hypot(p1[0]-p2[0], p1[1]-p2[1])

def get_distance3D(p1, p2):
    return np.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2 + (p1[2]-p2[2])**2)

# -------- 38.901 InH (Indoor-Office) PATH LOSS --------
def get_PL_LOS_InH(p1, p2, f_c):
    """
    3GPP TR 38.901 InH Office LOS:
      PL_LOS = 32.4 + 17.3*log10(d_3D) + 20*log10(fc_GHz), for 1 m <= d_3D <= 150 m
    """
    d_3D = get_distance3D(p1, p2)
    if d_3D < 1:  # spec validity starts at 1 m
        d_3D = 1.0
    if d_3D > 150:
        d_3D = 150.0
    fc_GHz = f_c * 1e-9
    PL_LOS = 32.4 + 17.3*math.log10(d_3D) + 20.0*math.log10(fc_GHz)
    return PL_LOS

def get_PL_NLOS_InH(p1, p2, f_c):
    """
    3GPP TR 38.901 InH Office NLOS (use max with LOS):
      PL'_NLOS = 38.3*log10(d_3D) + 17.30*log10(fc_GHz) + 24.9, for 1 m <= d_3D <= 150 m
      PL_NLOS = max(PL_LOS, PL'_NLOS)
    """
    d_3D = get_distance3D(p1, p2)
    if d_3D < 1:
        d_3D = 1.0
    if d_3D > 150:
        d_3D = 150.0
    fc_GHz = f_c * 1e-9
    PL_LOS = get_PL_LOS_InH(p1, p2, f_c)
    PLp_NLOS = 38.3*math.log10(d_3D) + 17.30*math.log10(fc_GHz) + 24.9
    return max(PL_LOS, PLp_NLOS)

# -------- LOS PROBABILITY (choose 'open' or 'mixed') --------
def get_Pr_InH(p1, p2, office_type='open'):
    """
    InH LOS probability from TR 38.901 Table 7.4.2-1.
    office_type: 'open' (default) or 'mixed'
    Uses d_in-2D (horizontal) in meters.
    """
    d = get_distance2D(p1, p2)
    if office_type == 'mixed':
        if d <= 1.2:
            return 1.0
        elif d < 6.5:
            return math.exp(-(d - 1.2)/4.7)
        else:
            return 0.32 * math.exp(-(d - 6.5)/32.6)
    else:  # 'open' office
        if d <= 5.0:
            return 1.0
        elif d < 49.0:
            return math.exp(-(d - 5.0)/70.0)
        else:
            return 0.54 * math.exp(-(d - 49.0)/211.7)

def get_PL_InH(p1, p2, f_c, office_type='open'):
    pr = get_Pr_InH(p1, p2, office_type)
    PL_los = get_PL_LOS_InH(p1, p2, f_c)
    PL_nlos = get_PL_NLOS_InH(p1, p2, f_c)
    return pr*PL_los + (1.0 - pr)*PL_nlos

def get_channel_gain_InH(p1, p2, f_c, office_type='open'):
    """
    Returns linear power gain g = 10^(-PL/10)
    """
    PL = get_PL_InH(p1, p2, f_c, office_type)
    return 10.0**(-PL/10.0)

def compute_c_bounds(h, P_max, eta):
    N = len(h)
    sum1 = np.sum(h * np.sqrt(P_max) / np.sqrt(eta))

    print("For number of transmitters: ",N)
    c_lower = 0
    for i in range(N):
        me = h[i] * np.sqrt(P_max[i]) / np.sqrt(eta)
        other = sum1 - me
        c_low = (np.sqrt(eta) / (2 * np.sqrt(P_max[i]) * np.abs(h[i]))) * np.exp(EXP_POWER_UTILITY * other)

        c_lower = max(c_lower, c_low)

    return c_lower

import numpy as np
import itertools

def compute_c_bounds_exhaustive(h, P_max, eta, step=0.1):
    """
    Compute c bounds by exhaustively searching all combinations of power values.
    We create for step=0.1 all combinations of P values between 0 and P_max. And for all of them calculate lower bound of c.
    We take max of lower bounds
    for N=100 it it 10^100 combinations so actually it is better ro aproximate using P_max
    """
    N = len(h)

    # Create power value ranges for each user
    power_ranges = []
    for i in range(N):
        # Generate power values from step to P_max[i] with step size
        power_values = np.arange(step, P_max[i] + step, step)
        power_ranges.append(power_values)

    c_lower = 0
    total_combinations = 1
    for i in range(N):
        total_combinations *= len(power_ranges[i])

    print(f"Total combinations to check: {total_combinations}")

    # Use itertools.product to generate all combinations
    for P_curr in itertools.product(*power_ranges):
        P_curr = np.array(P_curr)

        # Calculate the sum for this combination
        sum_val = np.sum(h * np.sqrt(P_curr) / np.sqrt(eta))

        # Calculate lower bound for each user
        for n in range(N):
            me = h[n] * np.sqrt(P_curr[n]) / np.sqrt(eta)
            other = sum_val - me
            low = (np.sqrt(eta) / (2 * np.sqrt(P_max[n]) * np.abs(h[n]))) * np.exp(EXP_POWER_UTILITY * other)
            c_lower = max(c_lower, low)

    return c_lower

import numpy as np
import numpy.typing as npt

# You can keep EXP_POWER_UTILITY defined globally
# Example: EXP_POWER_UTILITY = 0.1

MAX_EXP_SAFE = 709   # np.exp(709) ≈ 8.2e307
SAFE_MARGIN = 50     # clip range ±50 to keep np.exp stable

def safe_exp(x: np.ndarray) -> np.ndarray:
    """Safe exponential with clipping to avoid overflow."""
    return np.exp(np.clip(x, -SAFE_MARGIN, SAFE_MARGIN))


def utility_vector(
    P: npt.NDArray[np.float64],
    h: npt.NDArray[np.float64],
    c: np.float64,
    eta: np.float64
):
    utilities = np.zeros(len(P))
    sum1 = 0.0
    for i in range(len(P)):
        sum1 += h[i] * np.sqrt(P[i]) / np.sqrt(eta)

    # Compute adaptive safety scaling
    max_other = 0.0
    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        max_other = max(max_other, abs(other))

    safe_limit = SAFE_MARGIN / (2 * max_other) if max_other > 0 else 1.0
    global EXP_POWER_UTILITY
    if EXP_POWER_UTILITY > safe_limit:
        print(f"EXP_POWER_UTILITY ({EXP_POWER_UTILITY}) too large for data; "
              f"reducing to {safe_limit:.4e}.")
        EXP_POWER_UTILITY = safe_limit

    # Compute utilities safely
    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        exp_arg = EXP_POWER_UTILITY * other
        utilities[i] = me * safe_exp(exp_arg) - c * np.power(me, 2)

    return utilities


def closed_form_p_star(
    h: npt.NDArray[np.float64],
    c: np.float64,
    eta: np.float64,
    P_max: npt.NDArray[np.float64],
    P: npt.NDArray[np.float64]
):
    sum1 = 0.0
    for i in range(len(P)):
        sum1 += h[i] * np.sqrt(P[i]) / np.sqrt(eta)

    P_star = np.zeros(len(P))

    # Compute adaptive safety scaling
    max_other = 0.0
    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        max_other = max(max_other, abs(other))

    safe_limit = SAFE_MARGIN / (2 * max_other) if max_other > 0 else 1.0
    global EXP_POWER_UTILITY
    if EXP_POWER_UTILITY > safe_limit:
        print(f" EXP_POWER_UTILITY ({EXP_POWER_UTILITY}) too large deba for data; "
              f"reducing to {safe_limit:.4e}.")
        EXP_POWER_UTILITY = safe_limit

    # Compute P_star safely
    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        exp_arg2 = 2 * EXP_POWER_UTILITY * other
        P_star[i] = eta * safe_exp(exp_arg2) / (4 * np.power(c, 2) * np.power(h[i], 2))

    P_star = np.clip(P_star, 0, P_max)
    return P_star

def optimal_eta(h, P, sigma2):

    h = np.array(h)
    P = np.array(P)

    numerator = np.sum(h**2 * P) + sigma2
    denominator = np.sum(h * np.sqrt(P))

    eta_star = (numerator / denominator)**2
    return eta_star
#sigma2= 10e-12

import numpy as np
import pandas as pd
import time

# ----- Best Response Subroutine -----
def best_response(P_init, h, eta, c, epsilon_p, P_max_vec, max_iter_inner):
    """
    Inner loop: iterates over P until convergence.
    """
    P_current = P_init.copy()
    utilities_prev = utility_vector(P_current, h, c, eta)
    utility_history = [utilities_prev.copy()]
    power_history = [P_current.copy()]

    for iteration in range(max_iter_inner):
        P_new = closed_form_p_star(h, c, eta, P_max_vec, P_current)
        utilities_new = utility_vector(P_new, h, c, eta)

        power_history.append(P_new.copy())
        utility_history.append(utilities_new.copy())

        # Check convergence in power
        if np.linalg.norm(P_new - P_current) < epsilon_p:
            break

        P_current = P_new

    return P_new, utilities_new, np.array(power_history), np.array(utility_history), iteration + 1

import numpy as np
import pandas as pd
import time

def adaptive_eta_best_response(
    h: np.ndarray,
    eta_init: float,
    epsilon_p: float,
    epsilon_eta: float,
    P_max: np.ndarray,
):
    """
    Adaptive Best Response Algorithm with outer η-convergence loop
    (no max_iter limits — uses epsilon-based stopping).
    """
    # Initialize constants
    c = np.float64(8022291587.0)
    eta_current = eta_init
    iteration_eta = 0
    convergence_eta = 0

    # Initialize data storage
    eta_history = [eta_current]
    mse_history = []
    power_outer_history = []
    utility_outer_history = []

    # Outer loop (η convergence)
    start_time = time.time()

    # Initialize P randomly for the first iteration
    P_current = np.random.uniform(0, P_max, len(h))
    utility_history = [utility_vector(P_current, h, c, eta_current)]
    power_history = [P_current.copy()]

    while convergence_eta == 0:
        iteration_eta += 1
        print(f"\n=== η Iteration {iteration_eta} | Current η = {eta_current:.4e} ===")

        # ----- Inner loop: Best Response on Power -----
        convergence_p = 0
        iteration_p = 0

        while convergence_p == 0:
            iteration_p += 1

            P_new = closed_form_p_star(h, c, eta_current, P_max, P_current)
            utility_new = utility_vector(P_new, h, c, eta_current)

            power_history.append(P_new.copy())
            utility_history.append(utility_new.copy())

            # Check convergence in Power
            all_satisfy_epsilon_p = 1
            for i in range(len(P_current)):
                if np.abs(P_new[i] - P_current[i]) >= epsilon_p:
                    all_satisfy_epsilon_p = 0

            if all_satisfy_epsilon_p:
                convergence_p = 1
            else:
                P_current = P_new

        # ----- After Power Convergence -----
        P_star = P_new.copy()
        power_outer_history.append(P_star)
        utility_outer_history.append(utility_new)

        # Compute η* (replace with your formula later)
        eta_new = optimal_eta(h,P_star, 0)  # <--- your η update function

        # Compute MSE between consecutive P*(η)
        if iteration_eta > 1:
            mse_eta = np.mean((power_outer_history[-1] - power_outer_history[-2]) ** 2)
            mse_history.append(mse_eta)
            print(f"MSE(η): {mse_eta:.6e}")

            # Check convergence in η
            if mse_eta < epsilon_eta:
                convergence_eta = 1
                print("Converged in η based on MSE threshold.")

        # Update η and continue
        eta_history.append(eta_new)
        eta_current = eta_new

    # ----- Final Results -----
    runtime = time.time() - start_time

    df = pd.DataFrame({
        "Node": np.arange(1, len(h) + 1),
        "Final Power P*": P_star,
        "Final Utility": utility_new,
        "Channel Gain h": h,
    })

    return df, np.array(eta_history), np.array(mse_history), np.array(power_outer_history), runtime

c = np.float64(8022291587.0)
N = 10
P_max = np.ones(N)
x_positions = np.linspace(d_max/N, d_max, N)
transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]
epsilon_p=1e-15
epsilon_eta=1e-1

h = np.zeros(N)
for i in range(N):
    h[i] = get_channel_gain(transmitter_coordinates[i],receiver_coordinates,2405*10**6)

h

df, eta_history, mse_history, power_outer_history, runtime = adaptive_eta_best_response(
    h=h,
    eta_init=1.0,
    epsilon_p=epsilon_p,
    epsilon_eta=epsilon_eta,
    P_max=P_max
)

mse_history

