# -*- coding: utf-8 -*-
"""Adaptive_eta_response_UPD_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZzpHz341bI1q2iMVOx1gEsi48oqPAzyK
"""

import numpy as np
import math
import numpy.typing as npt
import pandas as pd
import time
import matplotlib.pyplot as plt

c_free = 3 * 10**8                                    # propagation velocity in the free space [m/s]
h_BS = 3.5                                       # antenna height of the base station [m]
h_UT = 3.5                                       # antenna height of the user terminal [m]
h_E = 1                                          # effective environment height [m]
h_prime_BS = h_BS - h_E                          # effective antenna height of the base station [m]
h_prime_UT = h_UT - h_E                          # effective antenna height of the user terminal [m]

def get_distance2D(p1, p2):
    d = np.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)
    return d

def get_distance3D(p1, p2):
    d = np.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2 + (p1[2] - p2[2]) ** 2)
    return d

def get_PL_LOS(p1, p2, f_c):
    d_2D = get_distance2D(p1, p2)
    d_3D = get_distance3D(p1, p2)
    d_BP = (4 * h_prime_BS * h_prime_UT * f_c) / c_free
    if (d_2D < 10):
        if (d_3D >= 1) and (d_3D <= 150):
            PL_LOS = 32.4 + 17.3*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9))
    else:
        if (d_2D >= 10) and (d_2D <= d_BP):
            PL_LOS = 32.4 + 21*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9))
        elif (d_2D >= d_BP) and (d_2D <= 5 * 10**3):
            PL_LOS = 32.4 + 40*math.log10(d_3D) + 20*math.log10(f_c * 10**(-9)) - 9.5*math.log10((d_BP)**2 + (p1[2] - p2[2])**2)
    return PL_LOS

def get_PL_NLOS(p1, p2, f_c):
    d_2D = get_distance2D(p1, p2)
    d_3D = get_distance3D(p1, p2)
    if (d_2D < 10):
        if (d_3D >= 1) and (d_3D <= 150):
            PL_prime_NLOS = 17.3 + 38.3*math.log10(d_3D) + 24.9*math.log10(f_c * 10**(-9))
    else:
        if (d_2D >= 10) and (d_2D <= 5 * 10**3):
            PL_prime_NLOS = 22.4 + 35.3*math.log10(d_3D) + 21.3*math.log10(f_c * 10**(-9)) - 0.3*(p2[2] - 1.5)
    PL_NLOS = max(get_PL_LOS(p1, p2, f_c), PL_prime_NLOS)
    return PL_NLOS

#this function gives the probability that how much of the transmission is in Line of Sight
def get_Pr(p1, p2):
    d_2D = get_distance2D(p1, p2)
    if (d_2D < 10):
        if (d_2D <= 1.2):
            pr_LOS = 1
        elif (d_2D > 1.2) and (d_2D < 6.5):
            pr_LOS = math.exp(-(d_2D - 1.2)/4.7)
        elif (d_2D >= 6.5):
            pr_LOS = math.exp(-(d_2D - 6.5)/32.6) * 0.32
    else:
        if d_2D <= 18:
            pr_LOS = 1
        elif d_2D > 18:
            pr_LOS = (18/d_2D) + (math.exp(-d_2D/36) * (1 - (18/d_2D)))
    return pr_LOS

def get_PL(p1, p2, f_c):
    PL = get_Pr(p1, p2) * get_PL_LOS(p1, p2, f_c) + (1 - get_Pr(p1, p2)) * get_PL_NLOS(p1, p2, f_c)
    return PL

def get_channel_gain(p1, p2, f_c):
    g = 1 / 10**(get_PL(p1, p2, f_c) / 10)
    return np.float64(g)



def get_distance2D(p1, p2):
    return np.hypot(p1[0]-p2[0], p1[1]-p2[1])

def get_distance3D(p1, p2):
    return np.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2 + (p1[2]-p2[2])**2)

# -------- 38.901 InH (Indoor-Office) PATH LOSS --------
def get_PL_LOS_InH(p1, p2, f_c):
    """
    3GPP TR 38.901 InH Office LOS:
      PL_LOS = 32.4 + 17.3*log10(d_3D) + 20*log10(fc_GHz), for 1 m <= d_3D <= 150 m
    """
    d_3D = get_distance3D(p1, p2)
    if d_3D < 1:  # spec validity starts at 1 m
        d_3D = 1.0
    if d_3D > 150:
        d_3D = 150.0
    fc_GHz = f_c * 1e-9
    PL_LOS = 32.4 + 17.3*math.log10(d_3D) + 20.0*math.log10(fc_GHz)
    return PL_LOS

def get_PL_NLOS_InH(p1, p2, f_c):
    """
    3GPP TR 38.901 InH Office NLOS (use max with LOS):
      PL'_NLOS = 38.3*log10(d_3D) + 17.30*log10(fc_GHz) + 24.9, for 1 m <= d_3D <= 150 m
      PL_NLOS = max(PL_LOS, PL'_NLOS)
    """
    d_3D = get_distance3D(p1, p2)
    if d_3D < 1:
        d_3D = 1.0
    if d_3D > 150:
        d_3D = 150.0
    fc_GHz = f_c * 1e-9
    PL_LOS = get_PL_LOS_InH(p1, p2, f_c)
    PLp_NLOS = 38.3*math.log10(d_3D) + 17.30*math.log10(fc_GHz) + 24.9
    return max(PL_LOS, PLp_NLOS)

# -------- LOS PROBABILITY (choose 'open' or 'mixed') --------
def get_Pr_InH(p1, p2, office_type='open'):
    """
    InH LOS probability from TR 38.901 Table 7.4.2-1.
    office_type: 'open' (default) or 'mixed'
    Uses d_in-2D (horizontal) in meters.
    """
    d = get_distance2D(p1, p2)
    if office_type == 'mixed':
        if d <= 1.2:
            return 1.0
        elif d < 6.5:
            return math.exp(-(d - 1.2)/4.7)
        else:
            return 0.32 * math.exp(-(d - 6.5)/32.6)
    else:  # 'open' office
        if d <= 5.0:
            return 1.0
        elif d < 49.0:
            return math.exp(-(d - 5.0)/70.0)
        else:
            return 0.54 * math.exp(-(d - 49.0)/211.7)

def get_PL_InH(p1, p2, f_c, office_type='open'):
    pr = get_Pr_InH(p1, p2, office_type)
    PL_los = get_PL_LOS_InH(p1, p2, f_c)
    PL_nlos = get_PL_NLOS_InH(p1, p2, f_c)
    return pr*PL_los + (1.0 - pr)*PL_nlos

def get_channel_gain_InH(p1, p2, f_c, office_type='open'):
    """
    Returns linear power gain g = 10^(-PL/10)
    """
    PL = get_PL_InH(p1, p2, f_c, office_type)
    return 10.0**(-PL/10.0)

def compute_c_bounds(h, P_max, eta):
    N = len(h)
    sum1 = np.sum(h * np.sqrt(P_max) / np.sqrt(eta))

    print("For number of transmitters: ",N)
    c_lower = 0
    for i in range(N):
        me = h[i] * np.sqrt(P_max[i]) / np.sqrt(eta)
        other = sum1 - me
        c_low = (np.sqrt(eta) / (2 * np.sqrt(P_max[i]) * np.abs(h[i]))) * np.exp(EXP_POWER_UTILITY * other)

        c_lower = max(c_lower, c_low)

    return c_lower

def utility_vector(
    P: npt.NDArray[np.float64],
    h: npt.NDArray[np.float64],
    c: np.float64,
    eta: np.float64
):
    utilities = np.zeros(len(P))
    sum1 = np.float64(0.0)
    for i in range(len(P)):
        sum1 += h[i] * np.sqrt(P[i]) / np.sqrt(eta)

    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        utilities[i] = me * np.exp(EXP_POWER_UTILITY *other) - c * np.power(me, 2)
    return utilities

def closed_form_p_star(
    h: npt.NDArray[np.float64],
    c: np.float64,
    eta: np.float64,
    P_max: npt.NDArray[np.float64],
    P: npt.NDArray[np.float64]
):
    sum1 = np.float64(0.0)
    for i in range(len(P)):
        sum1 += h[i] * np.sqrt(P[i]) / np.sqrt(eta)

    P_star = np.zeros(len(P))
    for i in range(len(P)):
        me = h[i] * np.sqrt(P[i]) / np.sqrt(eta)
        other = sum1 - me
        P_star[i] = eta * np.exp(2* EXP_POWER_UTILITY *other)/ (4 * np.power(c, 2) * np.power(h[i], 2))

    P_star = np.clip(P_star, 0, P_max)
    return P_star

def optimal_eta(h: npt.NDArray[np.float64], P: npt.NDArray[np.float64], sigma2: np.float64):
    num = np.float64(0.0)
    for i in range(len(h)):
        num += np.power(h[i], 2) * P[i]
    num += sigma2
    den = np.float64(0.0)
    for i in range(len(h)):
        den += h[i] * np.sqrt(P[i])

    eta_star = (num / den)**2
    return eta_star

def mse(P: npt.NDArray[np.float64], h: npt.NDArray[np.float64], eta: np.float64, sigma2: np.float64):
    mse = np.float64(0.0)
    for i in range(len(h)):
        mse += np.power(h[i] * np.sqrt(P[i]) / np.sqrt(eta) - np.float64(1.0), 2)
    mse += sigma2 / eta
    mse /= np.power(len(h), 2)
    return mse

def adaptive_eta_best_response(
    h: npt.NDArray[np.float64],
    eta_init: np.float64,
    epsilon_p: np.float64,
    epsilon_mse: np.float64,
    P_max: npt.NDArray[np.float64],
    sigma2: np.float64,
    c: np.float64,
    max_iter: int = 1000
):

    iteration_eta = 0
    convergence_eta = 0

    P_current = np.random.uniform(0, P_max, len(h))
    eta_current = eta_init

    eta_history: list[np.float64] = [eta_current]
    mse_history: list[np.float64] = [mse(P_current, h, eta_current, 0)]
    power_outer_history: list[list[npt.NDArray[np.float64]]] = []
    utility_outer_history: list[list[npt.NDArray[np.float64]]] = []

    while (convergence_eta == 0) and (iteration_eta < max_iter):
        iteration_eta += 1
        # print(f"\n=== η Iteration {iteration_eta} | Current η = {eta_current:.4e} ===")

        # ----- Inner loop: Best Response on Power -----
        convergence_p = 0
        iteration_p = 0

        power_history = []
        utility_history = []
        if iteration_eta == 0:
            utility_history.append(utility_vector(P_current, h, c, eta_current))
            power_history.append(P_current.copy())


        while (convergence_p == 0)and (iteration_p < max_iter) :
            iteration_p += 1

            P_new = closed_form_p_star(h, c, eta_current, P_max, P_current)
            utility_new = utility_vector(P_new, h, c, eta_current)

            power_history.append(P_new.copy())
            utility_history.append(utility_new.copy())

            # Check convergence in Power
            all_satisfy_epsilon_p = 1
            for i in range(len(P_current)):
                if np.abs(P_new[i] - P_current[i]) >= epsilon_p:
                    all_satisfy_epsilon_p = 0

            if all_satisfy_epsilon_p:
                convergence_p = 1

            P_current = P_new

        # ----- After Power Convergence -----
        P_star = P_current.copy()
        power_outer_history.append(power_history)
        utility_outer_history.append(utility_history)

        # Compute η
        eta_new = optimal_eta(h, P_star, sigma2)
        eta_history.append(eta_new)
        eta_current = eta_new

        # COMPUTE MSE
        mse_eta = mse(P_star, h, eta_current, sigma2)
        mse_history.append(mse_eta)


        # Print statements for debugging and tracking convergence
        # print(f"  → Inner loop converged in {iteration_p} iterations (ε_p={epsilon_p:.1e})")
        # if len(mse_history) > 1:
            # print(f"  → MSE difference from previous iteration: {np.abs(mse_history[-1] - mse_history[-2]):.4e}")

        if len(mse_history) > 1 and np.abs(mse_history[-1] - mse_history[-2]) < epsilon_mse:
            convergence_eta = 1
            # print("  ✓ Converged in η based on MSE threshold.")


    # print("\n=== Summary ===")
    # print(f"Total Outer Iterations: {iteration_eta}")
    # print(f"Average Inner Iterations per Outer: {np.mean([len(ph) for ph in power_outer_history]):.2f}")


    df = pd.DataFrame({
        "Node": np.arange(1, len(h) + 1),
        "Final Power P*": power_outer_history[-1][-1],
        "Final Utility": utility_outer_history[-1][-1],
        "Channel Gain h": h
    })

    return df, power_outer_history, utility_outer_history, mse_history, eta_history

N = 100
epsilon_p=1e-15
epsilon_mse=1e-6
sigma2=10e-13

EXP_POWER_UTILITY = 1 #if i change this there is huge difference
d_max = 100.0
P_max = np.ones(N).astype(np.float64)

receiver_coordinates = (0.0, 0.0, 0.0)
x_positions = np.linspace(d_max/N, d_max, N)
transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]
h = np.zeros(N)
for i in range(N):
    h[i] = get_channel_gain(transmitter_coordinates[i],receiver_coordinates,2405*10**6)


#c = np.float64(80022291587.0)
c = np.float64(200000.0)
#c = compute_c_bounds(h, P_max, np.float64(10e-10))
print(c)

start_time = time.time()
df, power_outer_history, utility_outer_history, mse_history, eta_history = adaptive_eta_best_response(
    h=h,
    eta_init=np.float64(1.0),
    epsilon_p=epsilon_p,
    epsilon_mse=epsilon_mse,
    P_max=P_max,
    sigma2=sigma2,
    c=c,
    max_iter=50
)
end_time = time.time()

complexity = end_time - start_time

# Combined plot with all 4 subplots
fig, axes = plt.subplots(2, 2, figsize=(15, 12))
fig.suptitle('Convergence Analysis', fontsize=16)

colors = plt.cm.tab10(np.linspace(0, 1, N))

# Plot 1: Power per node vs inner iteration (last outer iteration)
if len(power_outer_history) > 0:
    power_history = power_outer_history[-1]  # Last outer iteration
    ax1 = axes[0, 0]

    for node in range(N):
        node_powers = [power_history[inner_iter][node] for inner_iter in range(len(power_history))]
        ax1.plot(range(len(power_history)), node_powers, 'o-', color=colors[node],
                label=f'Node {node+1}', markersize=3, linewidth=1.5)

    ax1.set_xlabel('Inner Iteration')
    ax1.set_ylabel('Power')
    ax1.set_title('Power per Node vs Inner Iteration (Last Outer Iteration)')
    #ax1.legend()
    ax1.grid(True, alpha=0.3)

# Plot 2: Utility per node vs inner iteration (last outer iteration)
if len(utility_outer_history) > 0:
    utility_history = utility_outer_history[-1]  # Last outer iteration
    ax2 = axes[0, 1]

    for node in range(N):
        node_utilities = [utility_history[inner_iter][node] for inner_iter in range(len(utility_history))]
        ax2.plot(range(len(utility_history)), node_utilities, 'o-', color=colors[node],
                label=f'Node {node+1}', markersize=3, linewidth=1.5)

    ax2.set_xlabel('Inner Iteration')
    ax2.set_ylabel('Utility')
    ax2.set_title('Utility per Node vs Inner Iteration (Last Outer Iteration)')
    #ax2.legend()
    ax2.grid(True, alpha=0.3)

# Plot 3: MSE vs outer iteration
ax3 = axes[1, 0]
ax3.plot(range(len(mse_history)), mse_history, 'ro-', linewidth=2, markersize=5)
ax3.set_xlabel('Outer Iteration')
ax3.set_ylabel('MSE')
ax3.set_title('MSE vs Outer Iteration')
ax3.grid(True, alpha=0.3)

# Plot 4: ETA vs outer iteration
ax4 = axes[1, 1]
ax4.plot(range(len(eta_history)), eta_history, 'bo-', linewidth=2, markersize=5)
ax4.set_xlabel('Outer Iteration')
ax4.set_ylabel('ETA')
ax4.set_title('ETA vs Outer Iteration')
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print(df)
print("Final MSE: ", mse_history[-1])
print("Final ETA: ", eta_history[-1])
print("Time taken: ", complexity)
print("Number of outer iterations: ", len(power_outer_history))
print("Number of inner iterations: ", len(power_outer_history[0]))

mse_history

eta_history

"""AVERAGE MSE VS NUMBER OF USERS"""

N_values = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
avg_mse_values = []

for N in N_values:
    epsilon_p = 1e-15
    epsilon_mse = 1e-6
    sigma2 = 10e-13
    EXP_POWER_UTILITY = 1
    d_max = 100.0
    P_max = np.ones(N).astype(np.float64)

    receiver_coordinates = (0.0, 0.0, 0.0)
    x_positions = np.linspace(d_max / N, d_max, N)
    transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]
    h = np.zeros(N)
    for i in range(N):
        h[i] = get_channel_gain(transmitter_coordinates[i], receiver_coordinates, 2405 * 10**6)

    c = np.float64(200000.0)

    _, _, _, mse_history, _ = adaptive_eta_best_response(
        h=h,
        eta_init=np.float64(1.0),
        epsilon_p=epsilon_p,
        epsilon_mse=epsilon_mse,
        P_max=P_max,
        sigma2=sigma2,
        c=c,
        max_iter=50
    )

    avg_mse = np.mean(mse_history)
    avg_mse_values.append(avg_mse)

# Plot Average MSE vs Number of Users
plt.figure(figsize=(8, 6))
plt.plot(N_values, avg_mse_values, 'o-', color='purple', linewidth=2, markersize=8)
plt.xlabel('Number of Users (N)', fontsize=12)
plt.ylabel('Average MSE', fontsize=12)
plt.title('Average MSE vs Number of Users', fontsize=14)
plt.grid(True, alpha=0.3)
plt.show()

"""TIME OF STACKELBERG VS NUMBER OF USERS"""

N_values = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
time_values = []


for N in N_values:
    epsilon_p = 1e-15
    epsilon_mse = 1e-6
    sigma2 = 10e-13
    EXP_POWER_UTILITY = 1
    d_max = 100.0
    P_max = np.ones(N).astype(np.float64)

    receiver_coordinates = (0.0, 0.0, 0.0)
    x_positions = np.linspace(d_max / N, d_max, N)
    transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]
    h = np.zeros(N)
    for i in range(N):
        h[i] = get_channel_gain(transmitter_coordinates[i], receiver_coordinates, 2405 * 10**6)

    c = np.float64(200000.0)

    start_time = time.time()
    df, power_outer_history, utility_outer_history, mse_history, eta_history = adaptive_eta_best_response(
    h=h,
    eta_init=np.float64(1.0),
    epsilon_p=epsilon_p,
    epsilon_mse=epsilon_mse,
    P_max=P_max,
    sigma2=sigma2,
    c=c,
    max_iter=50
    )
    end_time = time.time()
    complexity = end_time - start_time
    time_values.append(complexity)

# Plot time vs Number of Users
plt.figure(figsize=(8, 6))
plt.plot(N_values, time_values, 'o-', color='purple', linewidth=2, markersize=8)
plt.xlabel('Number of Users (N)', fontsize=12)
plt.ylabel('Stackelberg Iterations', fontsize=12)
plt.title('Stackelberg Iterations vs Number of Users', fontsize=14)
plt.grid(True, alpha=0.3)
plt.show()

"""TIME OF STACKELBERG VS NUMBER OF USERS - MONTE CARLO"""

import numpy as np
import matplotlib.pyplot as plt
import time

# Monte Carlo settings
num_trials = 100  # number of Monte Carlo iterations per N
N_values = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
avg_time_values = []

for N in N_values:
    epsilon_p = 1e-15
    epsilon_mse = 1e-6
    sigma2 = 10e-13
    EXP_POWER_UTILITY = 1
    d_max = 100.0
    P_max = np.ones(N).astype(np.float64)
    c = np.float64(200000.0)

    # Store runtimes for each Monte Carlo trial
    monte_carlo_times = []

    for trial in range(num_trials):
        # Randomize transmitter positions slightly in each trial (optional)
        receiver_coordinates = (0.0, 0.0, 0.0)
        x_positions = np.linspace(d_max / N, d_max, N)
        transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]

        # Channel gains
        h = np.zeros(N)
        for i in range(N):
            h[i] = get_channel_gain(
                transmitter_coordinates[i],
                receiver_coordinates,
                2405 * 10**6
            )

        # Measure runtime
        start_time = time.time()
        df, power_outer_history, utility_outer_history, mse_history, eta_history = adaptive_eta_best_response(
            h=h,
            eta_init=np.float64(1.0),
            epsilon_p=epsilon_p,
            epsilon_mse=epsilon_mse,
            P_max=P_max,
            sigma2=sigma2,
            c=c,
            max_iter=50
        )
        end_time = time.time()

        monte_carlo_times.append(end_time - start_time)

    # Average runtime for this N
    avg_time = np.mean(monte_carlo_times)
    avg_time_values.append(avg_time)
    print(f"N={N}, Average Time={avg_time:.4f} seconds")

# Plot averaged time vs number of users
plt.figure(figsize=(8, 6))
plt.plot(N_values, avg_time_values, 'o-', color='purple', linewidth=2, markersize=8)
plt.xlabel('Number of Users (N)', fontsize=12)
plt.ylabel('Average Runtime (s)', fontsize=12)
plt.title('Average Runtime vs Number of Users (Monte Carlo Averaged)', fontsize=14)
plt.grid(True, alpha=0.3)
plt.show()





import numpy as np
import matplotlib.pyplot as plt
import time

# Monte Carlo settings
num_trials = 5
N_values = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

eta_indoor_avg = []
eta_outdoor_avg = []

for N in N_values:
    epsilon_p = 1e-15
    epsilon_mse = 1e-6
    sigma2 = 10e-13
    EXP_POWER_UTILITY = 1
    d_max = 100.0
    P_max = np.ones(N).astype(np.float64)
    c = np.float64(200000.0)
    receiver_coordinates = (0.0, 0.0, 0.0)
    x_positions = np.linspace(d_max / N, d_max, N)
    transmitter_coordinates = [(np.float64(x), 0.0, 0.0) for x in x_positions]

    eta_indoor_trials = []
    eta_outdoor_trials = []

    for trial in range(num_trials):
        # --- Indoor Channel ---
        h_indoor = np.zeros(N)
        for i in range(N):
            h_indoor[i] = get_channel_gain_InH(
                transmitter_coordinates[i],
                receiver_coordinates,
                2405 * 10**6
            )

        _, _, _, _, eta_history_in = adaptive_eta_best_response(
            h=h_indoor,
            eta_init=np.float64(1.0),
            epsilon_p=epsilon_p,
            epsilon_mse=epsilon_mse,
            P_max=P_max,
            sigma2=sigma2,
            c=c,
            max_iter=50
        )
        eta_indoor_trials.append(eta_history_in[-1])

        # --- Outdoor Channel ---
        h_outdoor = np.zeros(N)
        for i in range(N):
            h_outdoor[i] = get_channel_gain(
                transmitter_coordinates[i],
                receiver_coordinates,
                2405 * 10**6
            )

        _, _, _, _, eta_history_out = adaptive_eta_best_response(
            h=h_outdoor,
            eta_init=np.float64(1.0),
            epsilon_p=epsilon_p,
            epsilon_mse=epsilon_mse,
            P_max=P_max,
            sigma2=sigma2,
            c=c,
            max_iter=50
        )
        eta_outdoor_trials.append(eta_history_out[-1])

    # Take Monte Carlo averages
    eta_indoor_avg.append(np.mean(eta_indoor_trials))
    eta_outdoor_avg.append(np.mean(eta_outdoor_trials))

    print(f"N={N}: Indoor η = {eta_indoor_avg[-1]:.12f}, Outdoor η = {eta_outdoor_avg[-1]:.12f}")

# --- Plot ---
plt.figure(figsize=(8, 6))
plt.plot(N_values, eta_indoor_avg, 'o-', color='blue', linewidth=2, markersize=8, label='Indoor Channel')
plt.plot(N_values, eta_outdoor_avg, 's--', color='orange', linewidth=2, markersize=8, label='Outdoor Channel')
plt.xlabel('Number of Users (N)', fontsize=12)
plt.ylabel('Average η (Eta)', fontsize=12)
plt.title('Average Eta vs Number of Users (Indoor vs Outdoor)', fontsize=14)
plt.grid(True, alpha=0.3)
plt.legend(fontsize=11)
plt.show()

